### ISSUE TITLE
Hub panics when starting with dev consul

### ISSUE THREAD

**Issue by 3Hren** [sonm-io/core#141]
```bash
⇒  ./sonmhub
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x436c9f5]

goroutine 1 [running]:
testing.(*T).Log(0x0, 0xc42027ac10, 0x1, 0x1)
	<autogenerated>:9 +0x5
github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry.run.func1()
	/Users/esafronov/go/src/github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry/retry.go:116 +0x110
github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry.(*Timer).NextOr(0xc42023b4a0, 0xc42021eaa0, 0xc42027ab50)
	/Users/esafronov/go/src/github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry/retry.go:192 +0x120
github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry.run(0x4ba4f80, 0xc42023b4a0, 0x4bab480, 0x0, 0xc42021ea60)
	/Users/esafronov/go/src/github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry/retry.go:120 +0xd4
github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry.Run(0x4bab480, 0x0, 0xc42021ea60)
	/Users/esafronov/go/src/github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/retry/retry.go:85 +0x74
github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil.NewTestServerConfigT(0x0, 0xc42021ea40, 0x4693f60, 0xc420051901, 0xc42021ea40)
	/Users/esafronov/go/src/github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/server.go:210 +0xcf
github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil.NewTestServerConfig(0xc42021ea40, 0xc42021ea40, 0xc420051930, 0x449d2e8)
	/Users/esafronov/go/src/github.com/sonm-io/core/vendor/github.com/hashicorp/consul/testutil/server.go:195 +0x34
github.com/sonm-io/core/insonmnia/hub.newDevConsul(0x4baf100, 0xc42001b770, 0xc42001b770, 0x4baf100, 0xc42001b770)
	/Users/esafronov/go/src/github.com/sonm-io/core/insonmnia/hub/consul.go:52 +0x89
github.com/sonm-io/core/insonmnia/hub.New(0x5a612c0, 0xc42001b770, 0xc420095b80, 0x48b1630, 0x10, 0x0, 0x40116d2, 0x4c8fb00)
	/Users/esafronov/go/src/github.com/sonm-io/core/insonmnia/hub/server.go:729 +0x9b0
main.main()
	/Users/esafronov/go/src/github.com/sonm-io/core/cmd/hub/main.go:46 +0x1aa
```

**Comment by antmat** [comment]
It looks like for some reason dev-consul can not start and a bug in consul leads to nil dereference.

**Comment by antmat** [comment]
I think I can patch consul code, but I need to know to reproduce it

**Comment by 3Hren** [comment]
Nah, we just have a bad abstraction over consul. It is better to implement some kind of “no cluster” implementation
