### ISSUE TITLE
sonmoracle sends requests to sidechain which couldn't be fulfilled due to timeout

### ISSUE THREAD

**Issue by vakapral** [sonm-io/core#1872]
**Components version**
```bash
# /usr/bin/sonmoracle --version
oracle v0.4.0-7b8db826 (linux/amd64/go1.10.2)
```

**Example of a request**
```{"jsonrpc":"2.0","id":12820,"method":"eth_getLogs","params":[{"address":["0x540eeffa179382dec38883a6776d22030acdc2ed"],"fromBlock":"0x0","toBlock":"latest","topics":[["0x4a504a94899432a9846e1aa406dceb1bcfd538bb839071d49d1e5e23f5be30ef","0xf6a317157440607f36269043eb55f1287a5a19ba2216afeab88cd46cbcfb88e9","0xc0ba8fe4b176c1714197d43b9cc6bcf797a4a7461c5fe8d0ef6e184ae7601e51","0x33e13ecb54c3076d8e8bb8c2881800a4d972b792045ffae98fdf46df365fed75","0x526441bb6c1aba3c9a4a6ca1d6545da9c2333c8c48343ef398eb858d72b79236","0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c","0xf39e6e1eb0edcf53c221607b54b00cd28f3196fed0a24994dc308b8f611b682d","0x8001553a916ef2f495d26a907cc54d96ed840d7bda71e73194bf5a9df7a76b90","0xa3f1ee9126a074d9326c682f561767f710e927faa811f7a99829d49dc421797a"]]}]}```

Only two sonmoracle instances are guilty in this behaviour: iolebedev and vakapral
I guess it could be due to these nodes were detached from the Internet several times.

**Comment by vakapral** [comment]
I've just found out that the behavior has started to happen after the April, 1st and there are oracle's logs beneath:


`Apr  1 14:47:38  sonmoracle[9925]: 2019-04-01T14:47:38.936Z#011WARN#011oracle/oracle.go:55#011failed to load price#011{"error": "Get https://api.coinmarketcap.com/v1/ticker/sonm/: read tcp my_ip:45770->104.17.139.178:443: read: connection reset by peer"}
Apr  1 14:47:51  sonmoracle[9925]: panic: runtime error: invalid memory address or nil pointer dereference
Apr  1 14:47:51  sonmoracle[9925]: #011/home/developer/buildAgent/work/d55e539d770fac93/src/github.com/sonm-io/core/insonmnia/oracle/oracle.go:223 +0x5f8
Apr  1 14:47:51  sonmoracle[9925]: #011/home/developer/buildAgent/work/d55e539d770fac93/src/github.com/sonm-io/core/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
Apr  1 14:47:51  sonmoracle[9925]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xaccd47]
Apr  1 14:47:51  sonmoracle[9925]: github.com/sonm-io/core/insonmnia/oracle.(*Oracle).listenEventsRoutine(0xc420546c40, 0xfebfa0, 0xc420546c80, 0xf746e8, 0xc42081d010)
Apr  1 14:47:51  systemd[1]: sonm-oracle.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr  1 14:47:51  sonmoracle[9925]: #011/home/developer/buildAgent/work/d55e539d770fac93/src/github.com/sonm-io/core/insonmnia/oracle/oracle.go:191 +0xb7
Apr  1 14:47:51  sonmoracle[9925]: #011/home/developer/buildAgent/work/d55e539d770fac93/src/github.com/sonm-io/core/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
Apr  1 14:47:51  sonmoracle[9925]: 2019-04-01T14:47:51.030Z#011DEBUG#011oracle/oracle.go:106#011new submission found#011{"event": {"Data":{"TransactionId":397052},"BlockNumber":8149195,"TS":1554130070}}
Apr  1 14:47:51  sonmoracle[9925]: github.com/sonm-io/core/insonmnia/oracle.(*Oracle).transactionValid(0xc420546c40, 0xfebfa0, 0xc420546c80, 0xc4203a6120, 0x1)
Apr  1 14:47:51  sonmoracle[9925]: created by github.com/sonm-io/core/vendor/golang.org/x/sync/errgroup.(*Group).Go
Apr  1 14:47:51  sonmoracle[9925]: goroutine 89 [running]:
Apr  1 14:47:51  sonmoracle[9925]: #011/home/developer/buildAgent/work/d55e539d770fac93/src/github.com/sonm-io/core/insonmnia/oracle/oracle.go:107 +0x42e
Apr  1 14:47:51  systemd[1]: sonm-oracle.service: Unit entered failed state.
Apr  1 14:47:51  sonmoracle[9925]: math/big.(*Int).Set(...)
Apr  1 14:47:51  sonmoracle[9925]: github.com/sonm-io/core/insonmnia/oracle.(*Oracle).Serve.func3(0xc400000008, 0xf74708)
Apr  1 14:47:51  systemd[1]: sonm-oracle.service: Failed with result 'exit-code'.
Apr  1 14:47:51  sonmoracle[9925]: #011/usr/local/go/src/math/big/int.go:68
Apr  1 14:47:51  sonmoracle[9925]: github.com/sonm-io/core/insonmnia/oracle.(*Oracle).checkPrice(0xc420546c40, 0xc4203a6480, 0x0)
Apr  1 14:47:51  sonmoracle[9925]: #011/home/developer/buildAgent/work/d55e539d770fac93/src/github.com/sonm-io/core/insonmnia/oracle/oracle.go:145 +0x5f
Apr  1 14:47:51  sonmoracle[9925]: github.com/sonm-io/core/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc420546cc0, 0xc420a85ad0)
Apr  1 14:47:51  systemd[1]: sonm-oracle.service: Service hold-off time over, scheduling restart.`
